<a href="https://colab.research.google.com/github/Vipransh-Agarwal/House-Price-Prediction/blob/main/HousePricePred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from keras.callbacks import ModelCheckpoint
from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten
from sklearn.metrics import mean_absolute_error

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/data/train.csv')
train_set = dataset.drop(columns=['Id'])
col = train_set.select_dtypes(include=['object']).columns
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for feat in col:
    train_set[feat] = le.fit_transform(train_set[feat].astype(str))
x = train_set.iloc[:, :-1].values
y = train_set.iloc[:, -1].values


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='constant', fill_value=0)
imputer.fit(x)
x = imputer.transform(x)

In [ ]:
model = Sequential()
model.add(Dense(128, kernel_initializer='normal',input_dim = x.shape[1], activation='relu'))
model.add(Dense(256, kernel_initializer='normal',activation='relu'))
model.add(Dense(256, kernel_initializer='normal',activation='relu'))
model.add(Dense(256, kernel_initializer='normal',activation='relu'))
model.add(Dense(1, kernel_initializer='normal',activation='linear'))
model.compile(loss='mean_absolute_error', optimizer='adam', metrics=['mean_absolute_error'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               10240     
                                                                 
 dense_1 (Dense)             (None, 256)               33024     
                                                                 
 dense_2 (Dense)             (None, 256)               65792     
                                                                 
 dense_3 (Dense)             (None, 256)               65792     
                                                                 
 dense_4 (Dense)             (None, 1)                 257       
                                                                 
Total params: 175,105
Trainable params: 175,105
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(x, y, epochs=500, batch_size=32, validation_split = 0.2)

Epoch 1/500
37/37 [==============================] - 0s 5ms/step - loss: 29751.1953 - mean_absolute_error: 29751.1953 - val_loss: 32411.0176 - val_mean_absolute_error: 32411.0176
Epoch 2/500
37/37 [==============================] - 0s 5ms/step - loss: 29352.9414 - mean_absolute_error: 29352.9414 - val_loss: 32150.6602 - val_mean_absolute_error: 32150.6602
Epoch 3/500
37/37 [==============================] - 0s 5ms/step - loss: 27578.1016 - mean_absolute_error: 27578.1016 - val_loss: 30128.7129 - val_mean_absolute_error: 30128.7129
Epoch 4/500
37/37 [==============================] - 0s 5ms/step - loss: 26699.6016 - mean_absolute_error: 26699.6016 - val_loss: 30166.7988 - val_mean_absolute_error: 30166.7988
Epoch 5/500
37/37 [==============================] - 0s 5ms/step - loss: 26720.7148 - mean_absolute_error: 26720.7148 - val_loss: 30519.9961 - val_mean_absolute_error: 30519.9961
Epoch 6/500
37/37 [==============================] - 0s 5ms/step - loss: 26647.2012 - mean_absolute_error

In [ ]:
model.compile(loss='mean_absolute_error', optimizer='adam', metrics=['mean_absolute_error'])

In [ ]:
dataset2 = pd.read_csv('/content/drive/MyDrive/data/test.csv')
IDs = dataset2['Id'].tolist()
test_set = dataset2.drop(columns=['Id'])
col_t = test_set.select_dtypes(include=['object']).columns
from sklearn.preprocessing import LabelEncoder
le_t = LabelEncoder()
for feat in col_t:
    test_set[feat] = le_t.fit_transform(test_set[feat].astype(str))
x_t = test_set.values

In [ ]:
from sklearn.impute import SimpleImputer
imputer_t = SimpleImputer(missing_values=np.nan, strategy='constant', fill_value=0)
imputer_t.fit(x_t)
x_t = imputer_t.transform(x_t)
print(x_t)

[[2.000e+01 2.000e+00 8.000e+01 ... 2.010e+03 8.000e+00 4.000e+00]
 [2.000e+01 3.000e+00 8.100e+01 ... 2.010e+03 8.000e+00 4.000e+00]
 [6.000e+01 3.000e+00 7.400e+01 ... 2.010e+03 8.000e+00 4.000e+00]
 ...
 [2.000e+01 3.000e+00 1.600e+02 ... 2.006e+03 8.000e+00 0.000e+00]
 [8.500e+01 3.000e+00 6.200e+01 ... 2.006e+03 8.000e+00 4.000e+00]
 [6.000e+01 3.000e+00 7.400e+01 ... 2.006e+03 8.000e+00 4.000e+00]]


In [ ]:
predictions = model.predict(x_t)
print(predictions)

[[131530.47]
 [142184.19]
 [205909.55]
 ...
 [197469.89]
 [ 79731.46]
 [253214.89]]


In [ ]:
SalesPrice = []
for data in predictions.tolist():
    SalesPrice.append(data[0])
print(SalesPrice)

[131530.46875, 142184.1875, 205909.546875, 209297.578125, 192093.578125, 185880.265625, 178512.109375, 167402.140625, 179029.1875, 136829.078125, 229095.3125, 103708.9921875, 95197.2265625, 150888.328125, 108808.796875, 344240.0625, 245911.546875, 286631.90625, 278031.0, 548736.5, 321960.875, 202282.296875, 179424.765625, 163942.21875, 177015.40625, 201895.734375, 425830.875, 227330.828125, 210215.015625, 261691.890625, 200134.015625, 101883.3515625, 199286.578125, 297459.15625, 313669.15625, 258167.125, 168174.546875, 165803.21875, 153507.5, 163635.78125, 203460.828125, 149605.875, 325198.875, 235551.8125, 254713.484375, 183352.625, 294748.15625, 196391.015625, 163138.203125, 159686.109375, 148611.515625, 201687.765625, 151823.65625, 163280.921875, 191042.953125, 169816.703125, 180957.015625, 121374.9765625, 200667.1875, 138356.71875, 141783.796875, 180944.296875, 117817.8359375, 125115.09375, 126265.8828125, 121379.875, 109610.9609375, 135813.046875, 157119.609375, 184894.6875, 11705

In [ ]:
df = pd.DataFrame()
df.insert(0, 'Id', IDs, True)
df.insert(1, 'SalePrice', SalesPrice)
display(df)

Id      SalePrice
0     1461  131530.468750
1     1462  142184.187500
2     1463  205909.546875
3     1464  209297.578125
4     1465  192093.578125
...    ...            ...
1454  2915   93272.382812
1455  2916   87170.476562
1456  2917  197469.890625
1457  2918   79731.460938
1458  2919  253214.890625

[1459 rows x 2 columns]